Added an AttributeError exception handler in the editor autocompletion code because of the error below.  Some context, I am wrapping a new ui widget, put it in the init file, however, since I did this after starting the editor, it's imported libraries don't contain it.
Traceback (most recent call last):
  File "C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 1455
5, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Personal\dabo-full\trunk\dabo\ui\uiwx\dEditor.py", line 1238, in code
Complete
    obj = self._getRuntimeObject(self._getRuntimeObjectName())
  File "C:\Personal\dabo-full\trunk\dabo\ui\uiwx\dEditor.py", line 1814, in _get
RuntimeObject
    self._makeContainingClassIntoSelf()
  File "C:\Personal\dabo-full\trunk\dabo\ui\uiwx\dEditor.py", line 1785, in _mak
eContainingClassIntoSelf
    exec classdef in self._namespaces
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'dBorderlessButton'