Was getting the following:
  File "/home/pmcnett/dabo-full/trunk/dabo/db/dCursorMixin.py", line 270, in _correctFieldType
    scale = len(_field_val.split(".")[1])
AttributeError: 'int' object has no attribute 'split'

Because I guess sqlite's adapter returned the field as an int even though it can
contain decimal places. Adding the AttributeError fixes.