If the user clicks the close button instead of cancel on the new configure grid dialog, this traceback would occur:
Traceback (most recent call last):
  File "/home/pmcnett/dabo/dabo/ui/uiwx/dToolBar.py", line 486, in __onWxHit
    self.raiseEvent(dEvents.Hit)
  File "/home/pmcnett/dabo/dabo/lib/eventMixin.py", line 93, in raiseEvent
    bindingFunction(event)
  File "/home/pmcnett/dabo/dabo/lib/datanav/Form.py", line 278, in onConfigGrid
    if d.selectedColumns == None:
AttributeError: 'GridColumnsDialog' object has no attribute 'selectedColumns'
Fixed.