Fixed up dbFirebird to work with kinterbasdb 3.1.2, which doesn't have a type_conv key of 200. So, in that case mxDateTime is required, yet Ubuntu didn't identify that as a dependency as it should have, so I had to install it manually (apt-get install python-egenix-datetime).
Modified the firebird section of the dCursorMixin test to use Ed's 
unittesting server, as I haven't set mine up yet. None of the Firebird
tests passed. Instead, they raise the following exception:

Traceback (most recent call last):
  File "test_dCursorMixin.py", line 297, in setUp
    self.jobid = self.get_jobid()
  File "test_dCursorMixin.py", line 302, in get_jobid
    self.cur.execute("select gen_id(gen_jobid, 1) as nextval from rdb$database")
  File "/home/pmcnett/projects/dabo/dabo/db/dCursorMixin.py", line 256, in execute
    raise dException.DBQueryException(e, sql)
DBQueryException: (-104, 'isc_dsql_prepare: invalid request BLR at offset 69. generator GEN_JOBID is not defined. ')
SQL: select gen_id(gen_jobid, 1) as nextval from rdb$database