Thanks to Brandon Singer, I've fixed a problem where passing kwargs to the constructor of any dObject subclass would silently pass any unhandled kwargs. The fix to the base problem was easy, but it turns out lots of our code was relying on this. I fixed the obvious places (code that gets run from dabo/ui/uiwx/test.py) but I suspect I've missed a few. If you get the exception:
TypeError: __init__() got an unexpected keyword argument '<argument>'

then it is due to this fix.

The minesweeper demo uses dabo.fastNameSet when creating the squares, and
it turns out that when fastNameSet is True, autoBindEvents() doesn't run.
Fixed.