Fix Linux segmentation fault and Windows Fatal Error c0000005 that was happening on destruction of the main frame. This appears to be a problem way down in the bowels of wx that I exposed with yesterday's addition of the dPemMixin.__getattr__() code, which was doing a self.GetName() to be able to display the name of the object in the raised AttributeError exception. I think the base C++ object is already destroyed which resulted in GetName() segfaulting. My workaround saves self.GetName() to _name at opportune times, and __getattr__ uses the value of _name for the AttributeError.
Add class dPanel, and make dPage inherit from that instead of from
wx.Panel.