Changed the raiseEvent to call the event bindings in-stack again, as segfaults and illegal instructions were happening for inexplicable reasons.
FWIW, though, here is a traceback I'm getting with the current ClassDesigner,
after choosing 'dCommandButton' from the dropdown (this is after applying
this change; before, I got 'Illegal Instruction').

Traceback (most recent call last):
  File "ClassDesigner.py", line 580, in ?
    app.setup()
  File "/usr/lib/python2.3/site-packages/dabo/dApp.py", line 120, in setup
    self.uiApp.setup(self)
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/uiApp.py", line 45, in setup
    self.dApp.MainForm = dApp.MainFormClass()
  File "ClassDesigner.py", line 37, in __init__
    super(DesignerForm, self).__init__(parent=parent, properties=properties, *args, **kwargs)
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/dForm.py", line 44, in __init__
    fm.dFormMixin.__init__(self, preClass, parent, properties, *args, **kwargs)
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/dFormMixin.py", line 19, in __init__
    super(dFormMixin, self).__init__(preClass, parent, properties, *args, **kwargs)
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/dPemMixin.py", line 95, in __init__
    self._afterInit()
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/dForm.py", line 71, in _afterInit
    dForm.doDefault()
  File "/usr/lib/python2.3/site-packages/dabo/common/doDefaultMixin.py", line 61, in doDefault
    return eval("super(cls, self).%s(*args, **kwargs)" % methodName)
  File "<string>", line 0, in ?
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/dFormMixin.py", line 43, in _afterInit
    super(dFormMixin, self)._afterInit()
  File "/usr/lib/python2.3/site-packages/dabo/ui/uiwx/dPemMixin.py", line 166, in _afterInit
    self.afterInit()
  File "ClassDesigner.py", line 89, in afterInit
    self.newClass(self._selectedClass)
  File "ClassDesigner.py", line 291, in newClass
    controlClass = self.getControlClass(cls)
  File "ClassDesigner.py", line 316, in getControlClass
    class controlMix(DesignerMixin, base, proxy):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases