Attempting to fix a problem introduced 2008-06-25 with the removal of the bare except lines, that results in this traceback from the auto-api-doc generation:
Traceback (most recent call last):
  File "/root/py/updateDaboApiDoc.py", line 26, in <module>
    import makeDaboApiDoc
  File "/root/tmp/dabodoc/makeDaboApiDoc.py", line 373, in <module>
    html = getApiDoc(class_)
  File "/root/tmp/dabodoc/makeDaboApiDoc.py", line 341, in getApiDoc
    html += getExpandedEntries("Properties", propList)
  File "/root/tmp/dabodoc/makeDaboApiDoc.py", line 230, in getExpandedEntries
    d = cls.getPropertyInfo(prop)
  File "./dabo/dabo/ui/uiwx/dPemMixin.py", line 791, in getPropertyInfo
  File "./dabo/dabo/ui/dPemMixinBase.py", line 27, in getPropertyInfo
  File "./dabo/dabo/lib/propertyHelperMixin.py", line 306, in getPropertyInfo
  File "./dabo/dabo/ui/uiwx/dPemMixin.py", line 1717, in _getBackColor
TypeError: unbound method GetBackgroundColour() must be called with About instance as first argument (got nothing instead)