After much Googling, I found that the error reported in several cases when saving data:
DBQueryException: SQL logic error or missing database

was being caused by the way SQLite handles automatic transactions. Added the parameter 'isolation_level=None' to the connection string sets the behavior properly.

Please confirm with your applications.