Added more tests to dBizobj, after I realized that after a biz.saveAll(), the current row number wasn't being restored if the pk is auto-generated by the backend. Fixed in dBizobj: used RowNumber instead, which doesn't change after a save.
Made dBackend raise a ValueError if AutoCommit can't be set. Added appropriate
test for this case in the dCursorMixin test.

Fixed up the dCursorMixin test to mostly work with firebird. This required 
changing all the field names to lower from mixed-case, as firebird returns
all case-insensitive names as UPPER, and dabo lower()s it, and Python is
case-sensitive. I think in the future we need to define a case-insensitive
string type to use for field and table names as appropriate, but for now this
will do.

Now, only two tests fail for dbFirebird:

pmcnett@sol:~/projects/dabo/dabo/db$ python test/test_dCursorMixin.py 
E..F................................
======================================================================
ERROR: testMementos (__main__.Test_dCursorMixin_firebird)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dCursorMixin.py", line 237, in testMementos
    cur.save()
  File "/home/pmcnett/projects/dabo/dabo/db/dCursorMixin.py", line 1040, in save
    saverow(self.RowNumber)
  File "/home/pmcnett/projects/dabo/dabo/db/dCursorMixin.py", line 1015, in saverow
    raise dException.DBQueryException, e
DBQueryException: (-625, 'isc_dsql_execute: validation error for column JOBID, value "*** null ***". ')
SQL: insert into dabo_unittest_tbl (pk) values (NULL) 

======================================================================
FAIL: test_AutoSQL (__main__.Test_dCursorMixin_firebird)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_dCursorMixin.py", line 348, in test_AutoSQL
    self.assertEqual(cur.AutoSQL, "select first 1000 skip 0 *\n  from %s"
AssertionError: 'SELECT \n first 1000\n*\n  from dabo_unittest_tbl\n\n\n' != 'select first 1000 skip 0 *\n  from dabo_unittest_tbl'

----------------------------------------------------------------------
Ran 36 tests in 485.550s